language: cpp
cache: ccache
dist: bionic
osx_image: xcode11
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
  - sudo make install

matrix:
  exclude:
    - os: osx
      compiler: gcc
